"use client";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Providers } from "./providers";
import NavBar from "@/app/components/NavBar/NavBar";
import LoginModal from "@/app/components/NavBar/LoginModal";
import { useDisclosure } from "@heroui/modal";
import { useState } from "react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  const { onOpen, isOpen, onClose } = useDisclosure();
  // const isOpen = useState(true);
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Providers>
          <NavBar onPress={onOpen} />
          <LoginModal isOpen={isOpen} onClose={onClose} />
          {children}
        </Providers>
      </body>
    </html>
  );
}
